In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 10, (3, 5))

In [3]:
arr1

array([[9, 7, 9, 8, 7],
       [7, 2, 7, 8, 6],
       [5, 1, 5, 7, 8]])

In [4]:
arr1.reshape((5, -1))

array([[9, 7, 9],
       [8, 7, 7],
       [2, 7, 8],
       [6, 5, 1],
       [5, 7, 8]])

In [5]:
arr1.T

array([[9, 7, 5],
       [7, 2, 1],
       [9, 7, 5],
       [8, 8, 7],
       [7, 6, 8]])

In [6]:
arr1.flatten()

array([9, 7, 9, 8, 7, 7, 2, 7, 8, 6, 5, 1, 5, 7, 8])

In [7]:
arr1.shape

(3, 5)

In [8]:
np.expand_dims(arr1, axis = 1)

array([[[9, 7, 9, 8, 7]],

       [[7, 2, 7, 8, 6]],

       [[5, 1, 5, 7, 8]]])

In [9]:
np.expand_dims(arr1, axis = 1).shape

(3, 1, 5)

In [10]:
np.expand_dims(arr1, axis = 0)

array([[[9, 7, 9, 8, 7],
        [7, 2, 7, 8, 6],
        [5, 1, 5, 7, 8]]])

In [11]:
np.expand_dims(arr1, axis = 0).shape

(1, 3, 5)

In [12]:
np.squeeze(arr1)

array([[9, 7, 9, 8, 7],
       [7, 2, 7, 8, 6],
       [5, 1, 5, 7, 8]])

In [13]:
arr2 = np.array([[1], [2], [3, 4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [14]:
arr2 = np.array([[1], [2], [3]])

In [15]:
np.squeeze(arr2)

array([1, 2, 3])

In [16]:
np.squeeze(arr2)

array([1, 2, 3])

In [18]:
arr1

array([[9, 7, 9, 8, 7],
       [7, 2, 7, 8, 6],
       [5, 1, 5, 7, 8]])

In [17]:
np.repeat(arr1, 2)

array([9, 9, 7, 7, 9, 9, 8, 8, 7, 7, 7, 7, 2, 2, 7, 7, 8, 8, 6, 6, 5, 5,
       1, 1, 5, 5, 7, 7, 8, 8])

In [19]:
arr1

array([[9, 7, 9, 8, 7],
       [7, 2, 7, 8, 6],
       [5, 1, 5, 7, 8]])

In [20]:
np.roll(arr1, 2)

array([[7, 8, 9, 7, 9],
       [8, 7, 7, 2, 7],
       [8, 6, 5, 1, 5]])

In [22]:
arr3 = np.array([1, 2, 3, 4])

In [23]:
arr3

array([1, 2, 3, 4])

In [24]:
np.diag(arr3)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
arr4 = np.random.randint(1, 10, (3, 3))

In [28]:
arr5 = np.random.randint(1, 10, (3, 3))

In [29]:
arr4

array([[3, 4, 8],
       [5, 9, 5],
       [7, 4, 3]])

In [30]:
arr5

array([[6, 5, 3],
       [7, 4, 6],
       [7, 2, 6]])

In [31]:
arr4 + arr5

array([[ 9,  9, 11],
       [12, 13, 11],
       [14,  6,  9]])

In [33]:
arr4 * arr5

array([[18, 20, 24],
       [35, 36, 30],
       [49,  8, 18]])

In [34]:
arr4 - arr5

array([[-3, -1,  5],
       [-2,  5, -1],
       [ 0,  2, -3]])

In [36]:
arr4 % arr5

array([[3, 4, 2],
       [5, 1, 5],
       [0, 0, 3]])

In [37]:
arr4 @ arr5

array([[102,  47,  81],
       [128,  71,  99],
       [ 91,  57,  63]])

In [38]:
arr4 ^ arr5

array([[ 5,  1, 11],
       [ 2, 13,  3],
       [ 0,  6,  5]])

In [39]:
arr4 ** arr5

array([[   729,   1024,    512],
       [ 78125,   6561,  15625],
       [823543,     16,    729]])

~arr4

In [41]:
arr4 & arr5

array([[2, 4, 0],
       [5, 0, 4],
       [7, 0, 2]])

In [42]:
arr4 | arr5

array([[ 7,  5, 11],
       [ 7, 13,  7],
       [ 7,  6,  7]])

## Array of strings

In [44]:
arr6 = np.array(["Sri", "Darsan", "Sah"])

In [45]:
arr6

array(['Sri', 'Darsan', 'Sah'], dtype='<U6')

In [48]:
np.char.upper(arr6)

array(['SRI', 'DARSAN', 'SAH'], dtype='<U6')

In [49]:
np.char.lower(arr6)

array(['sri', 'darsan', 'sah'], dtype='<U6')

## Maths

In [50]:
arr4

array([[3, 4, 8],
       [5, 9, 5],
       [7, 4, 3]])

In [51]:
np.sin(arr4)

array([[ 0.14112001, -0.7568025 ,  0.98935825],
       [-0.95892427,  0.41211849, -0.95892427],
       [ 0.6569866 , -0.7568025 ,  0.14112001]])

In [52]:
np.tanh(arr4)

array([[0.99505475, 0.9993293 , 0.99999977],
       [0.9999092 , 0.99999997, 0.9999092 ],
       [0.99999834, 0.9993293 , 0.99505475]])

In [54]:
np.log10(arr4)

array([[0.47712125, 0.60205999, 0.90308999],
       [0.69897   , 0.95424251, 0.69897   ],
       [0.84509804, 0.60205999, 0.47712125]])

In [55]:
np.exp(arr4)

array([[  20.08553692,   54.59815003, 2980.95798704],
       [ 148.4131591 , 8103.08392758,  148.4131591 ],
       [1096.63315843,   54.59815003,   20.08553692]])

In [57]:
np.pow(arr4, 2)

array([[ 9, 16, 64],
       [25, 81, 25],
       [49, 16,  9]])

In [58]:
np.mean(arr4)

np.float64(5.333333333333333)

In [60]:
np.median(arr4)

np.float64(5.0)

In [61]:
np.std(arr4)

np.float64(2.0548046676563256)

In [ ]:
np