# Numpy

### METHODS TO CREATE ARRAYS

In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array([[1, 2], [3, 4]])

In [7]:
arr1

array([[1, 2],
       [3, 4]])

In [8]:
arr2 = np.array([[[1, 2, 3], [11, 12, 13]],[[4, 5, 6], [44, 55, 66]], [[7, 8, 9], [77, 88, 99]]])

In [9]:
arr2

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

In [10]:
arr3 = np.asarray([1, 2, 3])

In [11]:
arr3

array([1, 2, 3])

In [12]:
arr4 = np.asanyarray([1, 2, 3])

In [13]:
arr4

array([1, 2, 3])

In [14]:
mat1 = np.matrix([[1, 2, 3, 4], [11, 12, 13, 14]])

In [15]:
mat1

matrix([[ 1,  2,  3,  4],
        [11, 12, 13, 14]])

In [16]:
mat1.ndim

2

In [17]:
arr1.ndim

2

In [18]:
arr.ndim

1

In [19]:
arr2.ndim

3

In [20]:
mat2 = np.asanyarray(mat1)

In [21]:
mat2

matrix([[ 1,  2,  3,  4],
        [11, 12, 13, 14]])

In [22]:
l

[1, 2, 3, 4]

In [24]:
arr5 = np.asanyarray(l)

In [25]:
arr5

array([1, 2, 3, 4])

## CREATING COPIES

In [26]:
arr1

array([[1, 2],
       [3, 4]])

In [27]:
arr1_cpy = arr1

In [28]:
arr1[0][0] = 11

In [29]:
arr1

array([[11,  2],
       [ 3,  4]])

In [30]:
arr1_cpy

array([[11,  2],
       [ 3,  4]])

In [31]:
arr2_cpy = np.copy(arr2)

In [32]:
arr2

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

In [33]:
arr2[0][0][0] = 1111

In [34]:
arr2

array([[[1111,    2,    3],
        [  11,   12,   13]],

       [[   4,    5,    6],
        [  44,   55,   66]],

       [[   7,    8,    9],
        [  77,   88,   99]]])

In [35]:
arr2_cpy

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [44, 55, 66]],

       [[ 7,  8,  9],
        [77, 88, 99]]])

## GENERATING ARRAYS

In [36]:
arr6 = np.fromfunction(lambda i,j: i == j, (3, 4))

In [37]:
arr6

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [38]:
arr7 = np.fromfunction(lambda i,j: i * j, (3, 4))

In [39]:
arr7

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [41]:
itr1 = [i for i in range(5)]

In [42]:
itr1 

[0, 1, 2, 3, 4]

In [44]:
np.fromiter(itr1, float)

array([0., 1., 2., 3., 4.])

In [45]:
np.fromstring("11,12,13,14,15",sep=",")

array([11., 12., 13., 14., 15.])

## SIZE, DIMENSION AND SHAPE

In [47]:
arr

array([1, 2, 3, 4])

In [48]:
arr.ndim

1

In [49]:
arr1

array([[11,  2],
       [ 3,  4]])

In [50]:
arr1.ndim

2

In [51]:
arr2

array([[[1111,    2,    3],
        [  11,   12,   13]],

       [[   4,    5,    6],
        [  44,   55,   66]],

       [[   7,    8,    9],
        [  77,   88,   99]]])

In [52]:
arr2.ndim

3

In [53]:
arr1.dtype

dtype('int64')

In [55]:
arr2.size

18

In [56]:
arr2.shape

(3, 2, 3)

## ARRAYS WITH FLOAT VALUES

In [57]:
arr_flt = np.array([(1, 2, 3.0), (11, 12, 13)])

In [58]:
arr_flt

array([[ 1.,  2.,  3.],
       [11., 12., 13.]])

In [59]:
arr_flt.dtype

dtype('float64')

## MORE WAYS TO CREATE ARRAYS

In [60]:
np.arange(0, 100, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [61]:
list(np.arange(0, 10, 0.3))

[np.float64(0.0),
 np.float64(0.3),
 np.float64(0.6),
 np.float64(0.8999999999999999),
 np.float64(1.2),
 np.float64(1.5),
 np.float64(1.7999999999999998),
 np.float64(2.1),
 np.float64(2.4),
 np.float64(2.6999999999999997),
 np.float64(3.0),
 np.float64(3.3),
 np.float64(3.5999999999999996),
 np.float64(3.9),
 np.float64(4.2),
 np.float64(4.5),
 np.float64(4.8),
 np.float64(5.1),
 np.float64(5.3999999999999995),
 np.float64(5.7),
 np.float64(6.0),
 np.float64(6.3),
 np.float64(6.6),
 np.float64(6.8999999999999995),
 np.float64(7.199999999999999),
 np.float64(7.5),
 np.float64(7.8),
 np.float64(8.1),
 np.float64(8.4),
 np.float64(8.7),
 np.float64(9.0),
 np.float64(9.299999999999999),
 np.float64(9.6),
 np.float64(9.9)]

In [62]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [63]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
np.empty((3, 5))

array([[4.8897514e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        6.3240403e-322]])

In [68]:
arr_test = np.eye(5)

In [69]:
arr_test

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
arr_test + 4

array([[5., 4., 4., 4., 4.],
       [4., 5., 4., 4., 4.],
       [4., 4., 5., 4., 4.],
       [4., 4., 4., 5., 4.],
       [4., 4., 4., 4., 5.]])

In [75]:
np.logspace(1, 10, 100, base=2)

array([   2.        ,    2.13008218,    2.26862504,    2.41617889,
          2.5733298 ,    2.74070197,    2.91896021,    3.10881256,
          3.31101312,    3.52636502,    3.75572364,    4.        ,
          4.26016436,    4.53725009,    4.83235778,    5.14665959,
          5.48140394,    5.83792042,    6.21762513,    6.62202624,
          7.05273004,    7.51144729,    8.        ,    8.52032872,
          9.07450018,    9.66471556,   10.29331918,   10.96280788,
         11.67584085,   12.43525025,   13.24405248,   14.10546008,
         15.02289457,   16.        ,   17.04065743,   18.14900036,
         19.32943111,   20.58663837,   21.92561576,   23.35168169,
         24.87050051,   26.48810496,   28.21092016,   30.04578914,
         32.        ,   34.08131486,   36.29800071,   38.65886222,
         41.17327674,   43.85123151,   46.70336338,   49.74100102,
         52.97620991,   56.42184032,   60.09157828,   64.        ,
         68.16262972,   72.59600142,   77.31772444,   82.34655

In [76]:
np.linspace(2, 1025, 100)

array([   2.        ,   12.33333333,   22.66666667,   33.        ,
         43.33333333,   53.66666667,   64.        ,   74.33333333,
         84.66666667,   95.        ,  105.33333333,  115.66666667,
        126.        ,  136.33333333,  146.66666667,  157.        ,
        167.33333333,  177.66666667,  188.        ,  198.33333333,
        208.66666667,  219.        ,  229.33333333,  239.66666667,
        250.        ,  260.33333333,  270.66666667,  281.        ,
        291.33333333,  301.66666667,  312.        ,  322.33333333,
        332.66666667,  343.        ,  353.33333333,  363.66666667,
        374.        ,  384.33333333,  394.66666667,  405.        ,
        415.33333333,  425.66666667,  436.        ,  446.33333333,
        456.66666667,  467.        ,  477.33333333,  487.66666667,
        498.        ,  508.33333333,  518.66666667,  529.        ,
        539.33333333,  549.66666667,  560.        ,  570.33333333,
        580.66666667,  591.        ,  601.33333333,  611.66666

## RANDOM DATA GENERATION

In [82]:
random_arr1 = np.random.randn(3, 4)

In [83]:
import pandas as pd

In [85]:
pd.DataFrame(random_arr1)

0         1         2         3
0  0.436061  0.216459 -0.887546  1.001947
1 -1.268603 -0.906696  0.141400  0.362884
2  0.021085  0.709329  3.140349  1.847444

In [86]:
random_arr2 = np.random.rand(3, 4)

In [87]:
pd.DataFrame(random_arr2)

0         1         2         3
0  0.374726  0.146741  0.665945  0.625643
1  0.508161  0.573112  0.680459  0.975987
2  0.661353  0.561123  0.786633  0.403503

In [90]:
random_arr3 = np.random.randint(1, 100, (4, 4))

In [91]:
random_arr3

array([[72, 88, 90,  2],
       [24, 88, 53, 29],
       [46, 10,  3, 81],
       [96, 50, 42, 85]])

In [93]:
pd.DataFrame(random_arr3).to_csv("test.csv")

## RESHAPE

In [94]:
random_arr3

array([[72, 88, 90,  2],
       [24, 88, 53, 29],
       [46, 10,  3, 81],
       [96, 50, 42, 85]])

In [95]:
random_arr3.reshape((2, 8))

array([[72, 88, 90,  2, 24, 88, 53, 29],
       [46, 10,  3, 81, 96, 50, 42, 85]])

In [96]:
random_arr3.reshape((5, -1))

ValueError: cannot reshape array of size 16 into shape (5,newaxis)

In [97]:
random_arr3.reshape((8, -1))

array([[72, 88],
       [90,  2],
       [24, 88],
       [53, 29],
       [46, 10],
       [ 3, 81],
       [96, 50],
       [42, 85]])

## SLICING

In [98]:
random_arr3

array([[72, 88, 90,  2],
       [24, 88, 53, 29],
       [46, 10,  3, 81],
       [96, 50, 42, 85]])

In [99]:
random_arr3[1:3,1:3]

array([[88, 53],
       [10,  3]])

In [104]:
random_arr3[ 1:3, [1,3]]

array([[88, 29],
       [10, 81]])

In [106]:
random_arr3[[1,2], [1,3]]

array([88, 81])

## APPLYING CONDITIONS

In [100]:
random_arr3

array([[72, 88, 90,  2],
       [24, 88, 53, 29],
       [46, 10,  3, 81],
       [96, 50, 42, 85]])

In [101]:
random_arr3 > 30

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [102]:
random_arr3[random_arr3 > 30]

array([72, 88, 90, 88, 53, 46, 81, 96, 50, 42, 85])

## OPERATIONS

In [107]:
arr1 = np.random.randint(1, 20, (3, 4))

In [108]:
arr1

array([[11,  6,  7,  5],
       [14, 10, 13, 13],
       [ 6,  9,  5, 11]])

In [109]:
arr2 = np.random.randint(1, 20, (3, 4))

In [110]:
arr2

array([[ 4, 14, 17,  5],
       [12, 11,  9, 17],
       [ 4, 15, 13,  9]])

In [111]:
arr1 + arr2

array([[15, 20, 24, 10],
       [26, 21, 22, 30],
       [10, 24, 18, 20]])

In [112]:
arr1 - arr2

array([[  7,  -8, -10,   0],
       [  2,  -1,   4,  -4],
       [  2,  -6,  -8,   2]])

In [113]:
arr1 / arr2

array([[2.75      , 0.42857143, 0.41176471, 1.        ],
       [1.16666667, 0.90909091, 1.44444444, 0.76470588],
       [1.5       , 0.6       , 0.38461538, 1.22222222]])

In [114]:
arr1 * arr2

array([[ 44,  84, 119,  25],
       [168, 110, 117, 221],
       [ 24, 135,  65,  99]])

In [115]:
arr1 @ arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [117]:
arr3 = np.random.randint(1, 20, (4, 3))

In [118]:
arr1 @ arr3

array([[297, 301, 300],
       [481, 490, 488],
       [265, 290, 250]])

In [ ]:
arr1.T

In [ ]:
np.exp(arr1)

In [ ]:
np.log10(arr1)

In [ ]:
np.sqrt(arr1)

## BROADCASTING

In [119]:
arr1 = np.random.randint(1, 50, (4, 4))

In [120]:
arr1

array([[39, 38, 47, 31],
       [12, 37, 21,  7],
       [11, 30, 42, 38],
       [16, 19, 28, 45]])

In [121]:
vect1 = np.array([1, 2, 3, 4])

In [122]:
arr1 + vect1

array([[40, 40, 50, 35],
       [13, 39, 24, 11],
       [12, 32, 45, 42],
       [17, 21, 31, 49]])

In [125]:
arr1 + vect1.reshape(4,-1)

array([[40, 39, 48, 32],
       [14, 39, 23,  9],
       [14, 33, 45, 41],
       [20, 23, 32, 49]])