In [1]:
import numpy as np

In [2]:
arr = np.random.randint(0, 100, (2, 3, 3))
arr

array([[[12, 16,  0],
        [68, 32, 94],
        [96, 10, 57]],

       [[52, 38, 37],
        [21, 65, 57],
        [28, 41, 65]]])

In [3]:
arr1 = np.random.randint(1, 10, size=10)

In [4]:
arr1

array([7, 9, 3, 6, 3, 5, 1, 4, 4, 4])

In [5]:
np.sort(arr1)

array([1, 3, 3, 4, 4, 4, 5, 6, 7, 9])

In [6]:
np.searchsorted(arr1, 3)

np.int64(0)

In [7]:
arr2 = np.random.randint(1, 100, size=(2,5))

In [8]:
arr2

array([[26, 63, 22,  7, 54],
       [ 5,  4, 30, 40, 84]])

In [9]:
arr3 = np.random.randint(0, 3, size=(4, 5))

In [10]:
arr3

array([[2, 1, 1, 2, 1],
       [0, 1, 2, 2, 0],
       [2, 1, 0, 2, 2],
       [0, 1, 1, 1, 2]])

In [11]:
np.count_nonzero(arr3)

16

In [12]:
np.where(arr3 > 0)

(array([0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 4, 1, 2, 3, 0, 1, 3, 4, 1, 2, 3, 4]))

In [13]:
np.extract(arr3 > 1, arr3)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
arr3.byteswap()

array([[144115188075855872,  72057594037927936,  72057594037927936,
        144115188075855872,  72057594037927936],
       [                 0,  72057594037927936, 144115188075855872,
        144115188075855872,                  0],
       [144115188075855872,  72057594037927936,                  0,
        144115188075855872, 144115188075855872],
       [                 0,  72057594037927936,  72057594037927936,
         72057594037927936, 144115188075855872]])

In [15]:
arr4 = arr3

In [16]:
arr3

array([[2, 1, 1, 2, 1],
       [0, 1, 2, 2, 0],
       [2, 1, 0, 2, 2],
       [0, 1, 1, 1, 2]])

In [17]:
arr4

array([[2, 1, 1, 2, 1],
       [0, 1, 2, 2, 0],
       [2, 1, 0, 2, 2],
       [0, 1, 1, 1, 2]])

In [18]:
arr3[0][0] = 33

In [19]:
arr3

array([[33,  1,  1,  2,  1],
       [ 0,  1,  2,  2,  0],
       [ 2,  1,  0,  2,  2],
       [ 0,  1,  1,  1,  2]])

In [20]:
arr4

array([[33,  1,  1,  2,  1],
       [ 0,  1,  2,  2,  0],
       [ 2,  1,  0,  2,  2],
       [ 0,  1,  1,  1,  2]])

In [21]:
arr5 = np.copy(arr3)

In [22]:
arr5[0][0] = 100

In [23]:
arr5

array([[100,   1,   1,   2,   1],
       [  0,   1,   2,   2,   0],
       [  2,   1,   0,   2,   2],
       [  0,   1,   1,   1,   2]])

In [24]:
arr4

array([[33,  1,  1,  2,  1],
       [ 0,  1,  2,  2,  0],
       [ 2,  1,  0,  2,  2],
       [ 0,  1,  1,  1,  2]])

In [25]:
arr6 = arr5.view()

In [26]:
arr6[0][0] = 200

In [27]:
arr6

array([[200,   1,   1,   2,   1],
       [  0,   1,   2,   2,   0],
       [  2,   1,   0,   2,   2],
       [  0,   1,   1,   1,   2]])

In [28]:
arr5

array([[200,   1,   1,   2,   1],
       [  0,   1,   2,   2,   0],
       [  2,   1,   0,   2,   2],
       [  0,   1,   1,   1,   2]])

In [29]:
import numpy.matlib as mt

In [30]:
mt.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
mt.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
mt.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
arr1 = np.random.randint([[11, 30], [50, 100]], 1000)

In [34]:
arr1

array([[ 46, 579],
       [531, 542]])

In [35]:
arr2 = np.random.randint([[11, 20], [100, 200]], [[100, 200], [1000, 2000]])

In [36]:
arr2

array([[  69,  174],
       [ 503, 1356]])

In [37]:
np.dot(arr1,arr2)

array([[294411, 793128],
       [309265, 827346]])

In [38]:
arr1@arr2

array([[294411, 793128],
       [309265, 827346]])